### ISSUE TITLE
Add a table of contents for lab pages

### ISSUE THREAD

**Issue by edricx** [0xcf/decal-web#204]
Some of the labs have lengthy lecture notes built into the lab, with the actual lab questions at the end of the page. ([Example: lab b3](https://decal.ocf.berkeley.edu/labs/b3)) A table of contents to skip to different sections on the page would make navigating these labs easier. We should add an auto-generated table of contents sidebar on each lab page.

**Comment by BernardZhao** [comment]
Another feature we can add is advanced code highlighting to the code blocks, I think it's already built in.

**Comment by BernardZhao** [comment]
The table of contents is here! I guess we should add another issue so that in the future it can be a sidebar or something.
